[EOSF-677] Google Analytics on job links
CenterForOpenScience/cos.io pull request #890
Opened 2017-06-21 15:17 UTC by baylee-d

## Ticket

https://openscience.atlassian.net/browse/EOSF-677

## Purpose

To add Google Analytic tracking to outbound links on the job page.

## Changes

- Added a function to the html to track outbound links that call it on click.  
- Changed the Job model to use a RawHTML field instead of a RichTextField.  This will let you directly alter the links in 'Apply' section of the job description.
- Added migrations to help change the data to JSON.  That way previous text shouldn't have to be changed.

## Additional

- This fix only changes the structure of the model in preparation for Google Analytics to be added to links.  In order for it to be added to links, someone with Admin access will have to change the links to have an `onclick` function like this:
` <a href="http://www.example.com" onclick="trackOutboundLink('http://www.example.com'); return false;">Check out example.com</a> `

This will make a call to the trackOutboundLink function and track the click in Google Analytics.

2017-07-18 15:44 UTC, jamescdavis requested changes
Please rename common/migrations/0054_auto_20170621_1404.py to 0054_description_of_what_this_does.py to identify this as a custom migration.

2017-07-18 15:44 UTC, jamescdavis commented on common/migrations/0054_auto_20170621_1404.py
> +# Generated by Django 1.10.2 on 2017-06-21 14:04
Remove this since you've customized it.

2017-07-19 13:52 UTC, jamescdavis commented
Should rebase and make sure migrations are ok.

2017-07-19 20:12 UTC, baylee-d commented
Migrations should be all up to date and in order now 👍

2017-07-21 16:57 UTC, jamescdavis approved these changes
Migrations look good now.

2017-07-24 17:42 UTC, merged